config/routes.rb
Rails.application.routes.draw do
    root to: 'top#index'
    
    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    

    resources :blogs do 
      collection do 
      post:confirm
      get :top
    end
  end
  
    resources :sessions, only: [:new, :create, :destroy]
    resources :users
    resources :favorites, only: [:create, :destroy]
    
    get '*path', controller: 'application', action: 'render_404'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
     mount_uploader :image, ImageUploader
    
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    belongs_to :user
    
    validates:title,presence:true
    validates :content, length:{in:1..140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader
    before_validation { email.downcase! }
    has_secure_password
    
    validates :password, presence: true, length: { minimum: 6 }
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    validates :image, presence: true

    has_many :blogs, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_blogs, through: :favorites, source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  # rescue_from ActiveRecord::RecordNotFound, with: :render_404
  # rescue_from ActionController::RoutingError, with: :render_404
  # rescue_from Exception, with: :render_500

  # def render_404
  # render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  # end

  # def render_500
  # render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  # end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    before_action :log_in?, only: [:new, :edit, :show, :destroy] 

    def index
        @blogs = Blog.all    
    end  
    
    def new
      if params[:back]
        @blog = Blog.new(blog_params)
      else
        @blog = Blog.new
      end
    end
    
    def confirm
        @blog = Blog.new(blog_params)
        @blog.user_id = current_user.id
        render :new if @blog.invalid?
    end
    
    def create
      @blog = Blog.new(blog_params)
      @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
      respond_to do |format|
        if @blog.save
          BlogMailer.blog_mail(@blog).deliver  ##追記
          format.html { redirect_to blogs_path(@blog), notice: 'Blog was successfully created.' }
          format.json { render :show, status: :created, location: @blog }
        else
          format.html { render :new }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
        
       
        @user = User.find_by(id: @blog.user_id)#9/8追加
    
    
      end
    end
    
    def edit
    end
    
    def show
        @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    end
    
    def update
        if @blog.update(blog_params)
            redirect_to blogs_path, notice:"update！"
        else
            render'edit'
        end
    end
    
    def destroy
        @blog.destroy
        redirect_to blogs_path, notice:"delete！"
    end

    private
    
    def log_in?
      if current_user.blank?
        redirect_to new_session_path
      end
    end
   
    def set_blog
        @blog = Blog.find(params[:id])
    end
  
    def blog_params
        params.require(:blog).permit(:name, :email, :title, :content, :image, :image_cache, :user_id)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんの写真をお気に入り！"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんの写真をお気に入り解除！"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      # ログイン成功した場合
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'# ログイン失敗した場合
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
    # ログアウトの処理
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
      else
        render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_blogs = @user.favorite_blogs
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:image )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
    current_user.present?
    end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <ul>
    <li><%= form.label :title %>
    <%= form.text_field :title %></li>
  </div>
  <div class="blog_title">
    <li><%= form.label :content %>
    <%= form.text_field :content %></li>
  </div>
  <div class="field">
  <li><%= form.label :image %>
  <%= form.file_field :image, id: :blog_image %>
  <%= form.hidden_field :image_cache %></li>
  </ul>
</div>

  <%= form.submit %>
<% end %>

<%= link_to "一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p class="post">画像:<%= image_tag(@blog.image) %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
   <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @blog.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image, id: :blog_image %>
      <%= image_tag(@blog.image.url) if @blog.image.url %>
    </div>
    
  <%= form.submit %>
  <% end %>

app/views/blogs/index.html.erb
<div class="container">
    <h1>POSTS</h1>
    <p><%= notice %></p>

    <article>
      <div class="content">
      <% @blogs.each do |blog| %>
        <ul class="row col-lg-6">
          <li class="user_info">
            <%= image_tag(blog.user.image.url) %>
            <span><%= blog.user.name %>'s posts </span>
          </li>
          
          <li class="aaa ">
            <%= image_tag blog.image %>
            <%= blog.title %>
            <%= blog.content %>
          </li>
          
    
          <li class="col-lg-4 col-xs-12 "><%= link_to "details", blog_path(blog.id), class: 'btn btn-info'%></li>
          <% if blog.user_id == current_user.id %>
          <li class="col-lg-4 col-xs-12 "><%= link_to "edit", edit_blog_path(blog.id), class: 'btn btn-info'%></li>
          <li class="col-lg-4 col-xs-12 "><%= link_to "delete", blog_path(blog.id), method: :delete , data: { confirm: '本当に削除していいですか？' },class: 'btn btn-info'%></li>
          
          
          <% end %>
          </ul>
      <% end %>
      </div>

    </article>
</div>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<h3>  title: <%= @blog.title %>
  content: <%= @blog.content %>
<p id="notice"><%= notice %></p>
  </h3>

<div class=post>Image:
  <%= image_tag @blog.image %>
</div>
  
  <h2><% if @favorite.present? %>
    <%= link_to '🖤', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to '♡', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
  </h2>
  
  <h5><%= link_to 'Edit', edit_blog_path(@blog) %></h5>
  <h5><%= link_to 'Back', blogs_path %></h5>

app/views/blogs/top.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Achieve</title>
    <link rel="stylesheet" href="normalize.css">
    <link rel="stylesheet" href="style.css">
</head>
<body>
  <section class="main-header">
    <%= image_tag("achieve.jpg") %>
  </section>
  <section class="about">
    <h1>About Achieve</h1>
    <p>
      Achieveは、受講生のために作成された、教材用アプリです。<br>
      Achieveを作り終えることで、SecondTeamに参加するための力を身につけることができます。
    </p>
    <p>
      Acheiveを一言で表すと、タスク管理アプリです。<br>
      チームメンバーが、今どのようなタスクを行っているかリアルタイムで把握することができます。
    </p>
  </section>
  <section class="row function">
    <h1>Function</h1>
    
    <div class="function-images">
      <div class="function-image">
        <%= image_tag("key.png") %>
        <p>ログイン機能</p>
      </div>
      
      <div class="function-image">
        <%= image_tag("mails.png") %>
        <p>メール送信機能</p>
      </div>
      
      <div class="function-image">
        <%= image_tag("girls.png") %>
        <p>友達つながり機能</p>
      </div>
      
      <div class="function-image">
        <%= image_tag("comment.png") %>
        <p>コメント投稿機能</p>
    </div>
  </section>
  
  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>INSTAGRAM</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
 
  <header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    
      <ul>
        <li><%= link_to image_tag("images.png"), new_blog_path %>
        <!--<span class="remark">投稿ここから</span>-->
        </li>
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
      </ul>
  
      <% else %>
      <h3><%= link_to "TOP", root_path %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
      </h3>
    <% end %>
    
    
  </header>
  
  <%= yield %>
  
  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</html>

app/views/top/index.html.erb
<div class="container">
	
	<section class="about">
    <h1>INSTAGRAM</h1>
    <p>写真を投稿しよう</p>
    
    <!--<div id="topnumber">-->
    <!--    <%#= image_tag("assets/images/insta.jpg") %>-->
    <!--</div>-->
    
    <div class="slide-show">
		<%= image_tag("/assets/images/insta0.jpg", class: 'active') %>
		<%= image_tag("/assets/images/insta1.jpg") %>
		<%= image_tag("/assets/images/insta2.jpg") %>
	</div>


<script>
    const images = document.querySelectorAll('.slide-show img');

let currentImage = 0;

window.setInterval(() => {

	images[currentImage].classList.remove('active');
	currentImage++;
	if (currentImage >= images.length) {
		currentImage = 0;
	}
	images[currentImage].classList.add('active');
}, 4000);

  </script>
  </section>
</div>  
  

app/views/users/new.html.erb
<h3>Sign up</h3>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="sign">
  <%= form_with(model: @user, local: true) do |f| %>
    <h5><%= f.label :name %>
      <%= f.text_field :name %>
    </h5>
    <h5>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </h5>
    <h5>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </h5>
    <h5>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </h5>
    <h5>
      <%= f.label :image_file, 'profile image' %>
      <%= f.file_field :image %>
    </h5>
    <%= f.submit "Create my account" %>
  <% end %>
  </div>

app/views/users/show.html.erb
<div class="container">
    
    <h3><%= link_to "みんなのPOSTS", blogs_path %></h3>

  <li class="a">
            <%= image_tag(@user.image.url) %>
            <span><<%= @user.name %>'s posts </span>
            mail:<%= @user.email %>
  </li>
          



<div class=like>
    <p><%=image_tag("like.gif") %>LIKE IT
    </p>
</div>

<% @favorites_blogs.each do |favorite| %>
<li class="post"><%= favorite.title %>
    <%= favorite.content %>
    <%= image_tag favorite.image %>
</li>

<% end %>

</div>